---
title: The beta is born
author: tercen
date: '2018-04-30'
slug: the-beta-is-born
categories: []
tags: []
---

We worked hard to incorporate all the great feedback we gathered over the last year, now we are delivering a have a great __beta__ version of the Tercen Cloud. We focussed on issues which researchers face day to day when dealing with large amount of data.

We are very proud to deliver the following:

* Easy one button installation for 
* New app store (i.e. library) on github
* Ability to import/export workflows
* New admin menu
  - Improved user management
  - New resource management (for CPU and Disk) 
* Upgraded user interface
  - New GUI access
  - New data table views
  - New progress bars
  - New logs
  - New scrolling modes
* Improved performance
* Github integration (for R code)
* New R code package management
* New full programmatic access to Tercen
  - New Tercen R package, called teRcen
* and more...

The __beta__ version is available on request just send an an email to `info@tercen.com`. We will supply you with links for download and documentation.

